apiVersion: v1
kind: Pod
metadata:
  # annotations:
  #   kubectl.kubernetes.io/last-applied-configuration: |
  #     {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"name":"faulty","namespace":"challenge"},"spec":{"containers":[{"image":"ghcr.io/iximiuz/labs/kubernetes-native-sidecars/app:v1.0.0","name":"app"}],"initContainers":[{"image":"ghcr.io/iximiuz/labs/kubernetes-native-sidecars/identity-provider:v1.0.0","name":"identity-provider"},{"image":"ghcr.io/iximiuz/labs/kubernetes-native-sidecars/announcer:v1.0.0","name":"announcer"}]}}
  # Please refer to this link to avoid error:
  # https://stackoverflow.com/questions/51297136/kubectl-error-the-object-has-been-modified-please-apply-your-changes-to-the-la
  # Remove these lines from the file:
  # - creationTimestamp:
  # - resourceVersion:
  # - selfLink:
  # - uid:
  # generation: 1
  name: faulty
  namespace: challenge
spec:
  containers:
    - image: 'ghcr.io/iximiuz/labs/kubernetes-native-sidecars/app:v1.0.0'
      imagePullPolicy: IfNotPresent
      name: app
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kube-api-access-cxxdd
          readOnly: true
  # Add this policy
  restartPolicy: Always
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  initContainers:
    # move the identity-provider container here
    - image: 'ghcr.io/iximiuz/labs/kubernetes-native-sidecars/identity-provider:v1.0.0'
      imagePullPolicy: IfNotPresent
      name: identity-provider
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kube-api-access-cxxdd
          readOnly: true
      # Add this policy
      restartPolicy: Always
    - image: 'ghcr.io/iximiuz/labs/kubernetes-native-sidecars/announcer:v1.0.0'
      imagePullPolicy: IfNotPresent
      name: announcer
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kube-api-access-cxxdd
          readOnly: true
      # Add this policy
      restartPolicy: Always
  nodeName: kube-01
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
  volumes:
    - name: kube-api-access-cxxdd
      projected:
        defaultMode: 420
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              items:
                - key: ca.crt
                  path: ca.crt
              name: kube-root-ca.crt
          - downwardAPI:
              items:
                - fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
                  path: namespace
# status:
#   conditions:
#     - lastProbeTime: null
#       lastTransitionTime: '2025-06-15T09:12:06Z'
#       status: 'True'
#       type: PodReadyToStartContainers
#     - lastProbeTime: null
#       lastTransitionTime: '2025-06-15T09:11:50Z'
#       message: 'containers with incomplete status: [announcer]'
#       reason: ContainersNotInitialized
#       status: 'False'
#       type: Initialized
#     - lastProbeTime: null
#       lastTransitionTime: '2025-06-15T09:11:50Z'
#       message: 'containers with unready status: [app identity-provider]'
#       reason: ContainersNotReady
#       status: 'False'
#       type: Ready
#     - lastProbeTime: null
#       lastTransitionTime: '2025-06-15T09:11:50Z'
#       message: 'containers with unready status: [app identity-provider]'
#       reason: ContainersNotReady
#       status: 'False'
#       type: ContainersReady
#     - lastProbeTime: null
#       lastTransitionTime: '2025-06-15T09:11:50Z'
#       status: 'True'
#       type: PodScheduled
#   containerStatuses:
#     - image: 'ghcr.io/iximiuz/labs/kubernetes-native-sidecars/app:v1.0.0'
#       imageID: ''
#       lastState: {}
#       name: app
#       ready: false
#       restartCount: 0
#       started: false
#       state:
#         waiting:
#           reason: PodInitializing
#       volumeMounts:
#         - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
#           name: kube-api-access-cxxdd
#           readOnly: true
#           recursiveReadOnly: Disabled
#     - image: ghcr.io/iximiuz/labs/kubernetes-native-sidecars/identity-provider:v1.0.0
#       imageID: ''
#       lastState: {}
#       name: identity-provider
#       ready: false
#       restartCount: 0
#       started: false
#       state:
#         waiting:
#           reason: PodInitializing
#       volumeMounts:
#         - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
#           name: kube-api-access-cxxdd
#           readOnly: true
#           recursiveReadOnly: Disabled
#   hostIP: 172.16.0.2
#   hostIPs:
#     - ip: 172.16.0.2
#   initContainerStatuses:
#     - containerID: containerd://0a09243c554e1db0cdb3927e9b94b63ac6c84d27dae4b75526b3d9cf09342401
#       image: 'ghcr.io/iximiuz/labs/kubernetes-native-sidecars/announcer:v1.0.0'
#       imageID: sha256:a003799a62e9acc204aae121bbeb4b2db22404ef312dc18f204467dd8cf35a2a
#       lastState:
#         terminated:
#           containerID: containerd://0a09243c554e1db0cdb3927e9b94b63ac6c84d27dae4b75526b3d9cf09342401
#           exitCode: 1
#           finishedAt: '2025-06-15T09:12:06Z'
#           reason: Error
#           startedAt: '2025-06-15T09:12:06Z'
#       name: announcer
#       ready: false
#       resources: {}
#       restartCount: 1
#       started: false
#       state:
#         waiting:
#           message: back-off 10s restarting failed container=announcer pod=faulty_challenge(b12869d1-d3be-4232-a324-55a6be737b35)
#           reason: CrashLoopBackOff
#       user:
#         linux:
#           gid: 0
#           supplementalGroups:
#             - 0
#             - 1
#             - 2
#             - 3
#             - 4
#             - 6
#             - 10
#             - 11
#             - 20
#             - 26
#             - 27
#           uid: 0
#       volumeMounts:
#         - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
#           name: kube-api-access-cxxdd
#           readOnly: true
#           recursiveReadOnly: Disabled
#   phase: Pending
#   podIP: 10.42.0.4
#   podIPs:
#     - ip: 10.42.0.4
#   qosClass: BestEffort
#   startTime: '2025-06-15T09:11:50Z'