apiVersion: v1
kind: Pod
metadata:
  annotations: {}
  name: faulty
  namespace: challenge
spec:
  initContainers:
    - image: ghcr.io/iximiuz/labs/kubernetes-native-sidecars/identity-provider:v1.0.0
      name: identity-provider
      restartPolicy: Always
    - image: ghcr.io/iximiuz/labs/kubernetes-native-sidecars/announcer:v1.0.0
      name: announcer
  containers:
    - image: ghcr.io/iximiuz/labs/kubernetes-native-sidecars/app:v1.0.0
      name: app