apiVersion: apps/v1                                                              
kind: Deployment                                                                 
metadata:                                                                        
  annotations:                                                                   
    deployment.kubernetes.io/revision: "1"                                       
    kubectl.kubernetes.io/last-applied-configuration: |                          
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"l    abels":{"app":"memhog"},"name":"memhog","namespace":"default"},"spec":{"replicas"    :1,"selector":{"matchLabels":{"app":"memhog"}},"template":{"metadata":{"labels":{    "app":"memhog"}},"spec":{"containers":[{"image":"ghcr.io/iximiuz/labs/go-app-oom/    memhog:v1.0.0","name":"memhog","ports":[{"containerPort":8080}],"resources":{"lim    its":{"cpu":"1000m","memory":"512Mi"},"requests":{"cpu":"1000m","memory":"512Mi"}    }}]}}}}                                     
  # Please refer to this link to avoid error:
  # https://stackoverflow.com/questions/51297136/kubectl-error-the-object-has-been-modified-please-apply-your-changes-to-the-la
  # Remove these lines from the file:
  # - creationTimestamp:
  # - resourceVersion:
  # - selfLink:
  # - uid:
  generation: 1                                                                 
  labels:                                                                        
    app: memhog                                                                  
  name: memhog                                                                   
  namespace: default                                                                                               
spec:                                                                            
  progressDeadlineSeconds: 600                                                   
  replicas: 1                                                                    
  revisionHistoryLimit: 10                                                       
  selector:                                                                      
    matchLabels:                                                                 
      app: memhog                                                                
  strategy:                                                                      
    rollingUpdate:                                                               
      maxSurge: 25%                   
      maxUnavailable: 25%                                                        
    type: RollingUpdate                                                          
  template:                                                                      
    metadata:                                                                    
      creationTimestamp: null                                                    
      labels:                                                                    
        app: memhog                                                              
    spec:                                                                        
      containers:                                                                
      - image: ghcr.io/iximiuz/labs/go-app-oom/memhog:v1.0.0                     
        imagePullPolicy: IfNotPresent                                            
        name: memhog
        ###### Add these lines to solve the problem:
        env:
          - name: GOMEMLIMIT
            value: "480MiB"
        #####################################                                                     
        ports:                                                                   
        - containerPort: 8080                                                    
          protocol: TCP                                                          
        resources:                                                               
          limits:                                                                
            cpu: "1"                                                             
            memory: 512Mi                                                        
          requests:                                                              
            cpu: "1"                                                             
            memory: 512Mi                                                        
        terminationMessagePath: /dev/termination-log                             
        terminationMessagePolicy: File                                           
      dnsPolicy: ClusterFirst                                                    
      restartPolicy: Always                                                      
      schedulerName: default-scheduler
      securityContext: {}                                                        
      terminationGracePeriodSeconds: 30                                          
status:                                                                          
  conditions:                                                                    
  - lastTransitionTime: "2025-06-11T15:54:34Z"                                   
    lastUpdateTime: "2025-06-11T15:57:19Z"                                       
    message: ReplicaSet "memhog-697769f459" has successfully progressed.         
    reason: NewReplicaSetAvailable                                               
    status: "True"                                                               
    type: Progressing                                                            
  - lastTransitionTime: "2025-06-11T16:03:46Z"                                   
    lastUpdateTime: "2025-06-11T16:03:46Z"                                       
    message: Deployment does not have minimum availability.                      
    reason: MinimumReplicasUnavailable                                           
    status: "False"                                                              
    type: Available                                                              
  observedGeneration: 1                                                          
  replicas: 1                                                                    
  unavailableReplicas: 1                                                         
  updatedReplicas: 1